swagger: "2.0"
info:
  description: entry project
  version: "1.0.0"
  title: entrysns
host: "10.156.147.200:3000"
basePath: "/api"
tags:
  - name: "user"
    description: "User API"
  - name: "post"
    description: "Post API"
  - name: "follow"
    description: "Follow API"
  - name: "main"
    description: "main API"
schemes:
- "http"
paths:
  /user/exist:
    post:
      produces: 
        - "application/json"
      tags:
      - "user"
      summary: "닉네임, 이메일 중복 확인"
      description: "닉네임, 이메일 중복 확인"
      parameters:
        - name: "exist"
          in: "body"
          description: "User exist"
          schema: 
            type: "string"
            properties:
              nick:
                type: "string"
                example: "nick"
              email:
                type: "string"
                example: "email@gmail.com"
      responses:
        200:
          description: "중복 아님"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        409:
          description: "이메일 중복됨"
          schema:
            type: "object"
            properties:
              message: 
                type: "string"
        410:
          description: "닉네임 중복됨"
          schema:
            type: "object"
            properties:
              message: 
                type: "string"
  /user/send:
    post:
      produces: 
        - "application/json"
      tags:
      - "user"
      summary: "이메일 전송"
      description: "이메일 전송"
      parameters:
        - name: "email"
          in: "body"
          description: "User email"
          schema: 
            type: "string"
            properties:
              email:
                type: "string"
                example: "email@gmail.com"
      responses:
        200:
          description: "이메일 전송 성공"
        500:
          description: "이메일 전송 실패"
  /user/email:
    post:
      produces: 
        - "application/json"
      tags:
      - "user"
      summary: "이메일 인증"
      description: "이메일 인증"
      parameters:
        - name: "auth"
          in: "body"
          description: "User auth"
          schema: 
            type: "string"
            properties:
              auth:
                type: "string"
                example: "123456"
      responses:
        200:
          description: "이메일 인증 성공"
        403:
          description: "이메일 인증 실패"
  /user/register:
    post:
      produces: 
        - "application/json"
      tags:
      - "user"
      summary: "회원가입"
      description: "회원가입"
      parameters:
      - name: "register"
        in: "body"
        description: "User register"
        schema:
          type: "string"
          properties: 
            name: 
              type: "string"
              example: "name"
            nick:
              type: "string"
              example: "nick"
            email:
              type: "string"
              example: "email@gmail.com"
            password:
              type: "string"
              example: "password"
      responses:
        200:
          description: "회원가입 성공"
          schema:
            type: "object"
            properties:
              name:
                type: "string"
                example: "name"
              nick:
                type: "string"
                example: "nick"
              email:
                type: "string"
                example: "email@gmail.com"
              password:
                type: "string"
                example: "password"      
        500:
          description: "회원가입 실패"
  /user/profile/{nick}:
    post:
      produces: 
        - "application/json"
      consumes: 
        - "multipart/form-data"
      tags:
      - "user"
      summary: "프로필 사진"
      description: "프로필 사진"
      parameters:
      - name: "nick"
        in: "path"
        type: "string"
        description: "닉네임"
        required: true
      - name: "img"
        in: "formData"
        type: "file"
        description: "profile image"
      responses:
        200:
          description: "프로필 사진 설정 성공"
          schema:
            type: "object"
            properties:
              message: 
                type: "string"
                example: "success"
              profile:
                type: "string"
                example: "filename.png"
        500:
          description: "회원가입 실패"
  /user/login:
    post:
      produces: 
        - "application/json"
      tags:
      - "user"
      summary: "로그인"
      description: "로그인"
      parameters:
        - name: "login"
          in: "body"
          description: "User login"
          schema: 
            type: "string"
            properties:
              email:
                type: "string"
                example: "email@gmail.com"
              password:
                type: "string"
                example: "password"
      responses:
        200:
          description: "로그인 성공"
          schema: 
            type: "object"
            properties:
              access_token:
                type: "string"
                example: "access_token"
              refresh_token:
                type: "string"
                example: "refresh_token"
        403:
          description: "로그인 실패"
  /user/refresh:
    get:
      produces:
        - "application/json"
      tags:
      - "user"
      summary: "액세스 토큰 재발급"
      description: "액세스 토큰 재발급"
      parameters:
        - name: "x-refresh-token"
          in: "header"
          type: "string"
          description: "리프레쉬 토큰"
      responses:
        200:
          description: "액세스 토큰 재발급 성공"
          schema:
            type: "object"
            properties:
              access_token:
                type: "string"
                example: "access_token"
  /post/write:
    post:
      produces: 
        - "application/json"
      consumes: 
        - "multipart/form-data"
      tags:
      - "post"
      summary: "글 쓰기"
      description: "글 쓰기"
      parameters:
        - name: "content"
          in: "formData"
          type: "string"
          description: "post content"
        - name: "img"
          in: "formData"
          type: "file"
          description: "post image"
        - name: "x-access-token"
          in: "header"
          type: "string"
          description: "액세스 토큰"
      responses:
        200:
          description: "성공"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "success"
              nick:
                type: "string"
                example: "nick"
              content:
                type: "string"
                example: "content"
              img:
                type: "array"
                items:
                  type: "string"
                  example: "img.jpg"
              likeCount:
                type: "number"
                example: "1"
              like:
                type: "array"
                items:
                  type: "string"
                  example: "nick"
              date: 
                type: "string"
                example: "date"
        403:
          description: "로그인 되어있지 않음" 
        500:
          description: "실패"
  /post/delete/{_id}:
    delete:
      produces: 
        - "application/json"
      tags:
      - "post"
      summary: "글 삭제"
      description: "글 삭제"
      parameters:
        - name: "_id"
          in: "path"
          description: "글 아이디"
          type: "string"
          required: true
        - name: "x-access-token"
          in: "header"
          type: "string"
          description: "액세스 토큰"
        - name: "remove"
          in: "body"
          description: "글 삭제"
          schema: 
            type: "string"
            properties:
              nick:
                type: "string"
                example: "nick"
              title:
                type: "string"
                example: "title"
              content:
                type: "string"
                example: "content"
      responses:
        200:
          description: "성공"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "success"
              nick:
                type: "string"
                example: "nick"
              title:
                type: "string"
                example: "title"
              content:
                type: "string"
                example: "content"
        403:
          description: "로그인 되어있지 않음" 
        500:
          description: "실패"
  /post/like/{_id}:
    get:
      produces: 
        - "application/json"
      tags:
      - "post"
      summary: "글 좋아요"
      description: "글 좋아요"
      parameters:
        - name: "_id"
          in: "path"
          description: "글 아이디"
          type: "string"
          required: true
        - name: "x-access-token"
          in: "header"
          type: "string"
          description: "액세스 토큰"
      responses:
        200:
          description: "성공"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "success"
              like:
                type: "number"
                example: 1
        403:
          description: "로그인 되어있지 않음" 
        500:
          description: "실패"
  /follow/following/{nick}:
    get:
      produces:
      - "application/json"
      tags:
      - "follow"
      summary: "팔로우 신청"
      description: "팔로우 신청"
      parameters:
        - name: "nick"
          in: "path"
          description: "닉네임"
          type: "string"
          required: true
        - name: "x-access-token"
          in: "header"
          type: "string"
          description: "액세스 토큰"
      responses:
        200:
          description: "성공"
        403:
          description: "로그인 되어있지 않음"
        500:
          description: "실패"
  /follow/allowlist:
    get:
      produces:
      - "application/json"
      tags:
      - "follow"
      summary: "팔로우 신청 목록"
      description: "팔로우 신청 목록"
      parameters:
        - name: "x-access-token"
          in: "header"
          type: "string"
          description: "액세스 토큰"
      responses:
        200:
          description: "성공"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "success"
              list:
                type: "array"
                items:
                  type: "string"
        403:
          description: "로그인 되어있지 않음"
        500:
          description: "실패"
  /follow/allow:
    get:
      produces:
      - "application/json"
      tags:
      - "follow"
      summary: "팔로우 수락"
      description: "팔로우 수락"
      parameters:
        - name: "x-access-token"
          in: "header"
          type: "string"
          description: "액세스 토큰"
        - name: "nick"
          in: "path"
          type: "string"
          description: "닉네임"
          required: true
      responses:
        200:
          description: "성공"
        403:
          description: "로그인 되어있지 않음"
        500:
          description: "실패"
  /follow/reject:
    get:
      produces:
      - "application/json"
      tags:
      - "follow"
      summary: "팔로우 거절"
      description: "팔로우 거절"
      parameters:
        - name: "x-access-token"
          in: "header"
          type: "string"
          description: "액세스 토큰"
        - name: "nick"
          in: "path"
          type: "string"
          description: "닉네임"
          required: true
      responses:
        200:
          description: "성공"
        403:
          description: "로그인 되어있지 않음"
        500:
          description: "실패"
  /follow/unfollow:
    delete:
      produces:
      - "application/json"
      tags:
      - "follow"
      summary: "팔로우 취소"
      description: "팔로우 취소"
      parameters:
        - name: "x-access-token"
          in: "header"
          type: "string"
          description: "액세스 토큰"
        - name: "nick"
          in: "path"
          type: "string"
          description: "닉네임"
          required: true
      responses:
        200:
          description: "성공"
        403:
          description: "로그인 되어있지 않음"
        500:
          description: "실패"
  /follow/followlist:
    get:
      produces:
      - "application/json"
      tags:
      - "follow"
      summary: "팔로우 목록"
      description: "팔로우 목록"
      parameters:
        - name: "x-access-token"
          in: "header"
          type: "string"
          description: "액세스 토큰"
      responses:
        200:
          description: "성공"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "success"
              follow:
                type: "array"
                items:
                  type: "string"
                  example: "nick"
              following:
                type: "array"
                items:
                  type: "string"
                  example: "nick"
        403:
          description: "로그인 되어있지 않음"
        500:
          description: "실패"
  /main:
    get:
      produces: 
      - "application/json"
      tags: 
      - "main"
      summary: "메인 유저정보"
      description: "메인 유저정보"
      parameters:
        - name: "x-access-token"
          in: "header"
          type: "string"
          description: "액세스 토큰"
      responses:
        200:
          description: "성공"
          schema:
            type: "object"
            properties:
              nick:
                type: "string"
              name: 
                type: "string"
              email:
                type: "string"
              profile:
                type: "string"
        403:
          description: "로그인 되어있지 않음"
        500:
          description: "실패"       
  /main/post:
    get:
      produces: 
      - "application/json"
      tags: 
      - "main"
      summary: "메인 타임라인"
      description: "메인 타임라인"
      parameters:
        - name: "x-access-token"
          in: "header"
          type: "string"
          description: "액세스 토큰"
      responses:
        200:
          description: "성공"
          schema:
            type: "object"
            properties:
              post: 
                type: "array"
                items:
                  type: "object"
                  properties:
                    nick:
                      type: "string"
                      example: "nick"
                    content:
                      type: "string"
                      example: "content"
                    img:
                      type: "array"
                      items:
                          type: "string"
                    likeCount:
                      type: "number"
                      example: "1"
                    like:
                      type: "array"
                      items: 
                          type: "string"
                          example: "nick"
                    date:
                      type: "string"
                      example: "date"
                    isMine:
                      type: "boolean"
                      example: true
                    isLike:
                      type: "boolean"
                      example: true
        403:
          description: "로그인 되어있지 않음"
        500:
          description: "실패"        
  /profile/{nick}:
    get:
      produces:
      - "application/json"
      tags:
      - "profile"
      summary: "메인 유저정보"
      description: "메인 유저정보"
      parameters:
        - name: "x-access-token"
          in: "header"
          type: "string"
          description: "액세스 토큰"
        - name: "nick"
          in: "path"
          type: "string"
          description: "닉네임"
          required: true
      responses:
        200:
          description: "성공"
          schema:
            type: "object"
            properties:
              nick:
                type: "string"
              name: 
                type: "string"
              email:
                type: "string"
              profile:
                type: "string"
        403:
          description: "로그인 되어있지 않음"
        500:
          description: "실패"
